namespace BankCustomers.DTOs
{
    public class CreateUserDTO
    {
        public required string Name { get; set; }
        public required string Email { get; set; }
        public required string Address { get; set; }
        public required string Phone { get; set; }
    }

    public class UpdateUserDTO
    {
        public required string Address { get; set; }
        public required string Phone { get; set; }
    }

    // UserDTO (Response)
    public class UserDTO
    {
        public Guid Id { get; set; } // Auto-generated by the server
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? Address { get; set; }
        public string? Phone { get; set; }
        //public string? WalletAddress { get; set; }

        public List<WalletDTO> ? Wallets { get; set; }

    }
}
